model_name: "ibm-granite/granite-3.0-1b-a400m-instruct"  
model_specs:
  total_parameters: "1.3B"      
  active_parameters: "400M"     
  expert_count: 32             
  embedding_size: 1024          
  layer_count: 24               
  context_length: 4096          
  
fine_tuning:
  enabled: true
  epochs: 3
  batch_size: 4                 # Can potentially increase due to smaller model
  learning_rate: 5e-5
  lora_config:
    r: 16
    alpha: 32
    target_modules: ["experts", "gate", "q_proj", "v_proj"]  # Same targeting


rag:
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  chunk_size: 512
  chunk_overlap: 50
  top_k: 5
  code_indexing:
    enabled: "${CODE_RAG_ENABLED:false}"
    roots: ["${CODE_RAG_ROOT_1:./}"]
    exclude_globs: ["**/node_modules/**","**/venv/**","**/.git/**"]
    chunk_size: "${CODE_RAG_CHUNK_SIZE:1000}"
    chunk_overlap: "${CODE_RAG_CHUNK_OVERLAP:200}"
    max_results: "${CODE_RAG_MAX_RESULTS:10}"
    rank_weights:
      similarity: "${CODE_RAG_W_SIM:0.4}"
      quality: "${CODE_RAG_W_QUAL:0.3}"
      reusability: "${CODE_RAG_W_REUSE:0.3}"

cag:
  cache_size: 10000
  preload_patterns: true

teams:  
  - name: "ingest_team"
    connector:
      type: "github"
      base_url: "${JIRA_BASE_URL}"
      username: "${JIRA_USERNAME}"
      api_token: "${JIRA_API_TOKEN}"
      repo_owner: "${GITHUB_ORG}"
      repo_name: "ingest-repo"
      token: "${GITHUB_TOKEN}"
    rag_enabled: true
    cag_enabled: true
    auto_push: false
  
  - name: "assets_team"
    connector:
      type: "github"
      repo_owner: "${GITHUB_ORG}"
      repo_name: "assets-repo"
      token: "${GITHUB_TOKEN}"
    rag_enabled: true
    cag_enabled: true
    auto_push: false
  
  - name: "cms_team"
    connector:
      type: "github"
      repo_owner: "${GITHUB_ORG}"
      repo_name: "cms-repo"
      token: "${GITHUB_TOKEN}"
    rag_enabled: true
    cag_enabled: true
    auto_push: false

  - name: "playback_team"
    connector:
      type: "github"
      repo_owner: "${GITHUB_ORG}"
      repo_name: "playback-repo"
      token: "${GITHUB_TOKEN}"
    rag_enabled: true
    cag_enabled: true
    auto_push: false

  - name: "ads_team"
    connector:
      type: "github"
      repo_owner: "${GITHUB_ORG}"
      repo_name: "ads-repo"
      token: "${GITHUB_TOKEN}"
    rag_enabled: true
    cag_enabled: true
    auto_push: false