name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('granite-test-generator/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install minimal CI dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r granite-test-generator/requirements-ci.txt

      - name: Run tests with coverage (subproject)
        working-directory: granite-test-generator
        run: |
          coverage run -m pytest -q

      - name: Run root tests and combine coverage
        run: |
          coverage run -a -m pytest -q tests || true
          coverage xml -o coverage.xml
          coverage report -m --fail-under=24
          coverage html -d htmlcov

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error

      - name: Upload HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov
          if-no-files-found: error
